### ISSUE TITLE
Having a central widget without header

### ISSUE THREAD

**Issue by IkkiNit** [githubuser0xFFFF/Qt-Advanced-Docking-System#137]
Is it possible to have a flag in the manager to avoid having the bar (name, menu, etc) on a central widget if it's alone in the central area ?
As soon as another dock is put in the central widget, the bar is shown again. It is hidden again if one of the two docks are removed.

Just in order to simulate the fact that sometimes the central widget is not a really dock window.

This will permit to use your awesome library in those cases as well.

Thank you !

**Comment by githubuser0xFFFF** [comment]
This would be an option, but then it would not be possible to drag out the latest visible dock widget into a floating widget. But from reading your text, this widget would not be draggable or floatable anyway. So this is mainly a cosmetic issue because you do not want to see the titlbar if only one widget is visible in main window - like it is already implemented if there is only one widget in a floating window. Is this right?

**Comment by IkkiNit** [comment]
Yes you are right the main widget in the central widget is not movable, floatable or closable.

**Comment by githubuser0xFFFF** [comment]
Added new config flag `HideSingleCentralWidgetTitleBar` in commit a668fe2f739608055698e50e8bcdac6caa716bde that enables this requested feature.
