### ISSUE TITLE
Set eventFilter() on CDockWidget

### ISSUE THREAD

**Issue by KerimMatlab** [githubuser0xFFFF/Qt-Advanced-Docking-System#165]
I use ADS from branch `focused_dockwidget`

I'm trying to set `eventFilter` on `CDockWidget` and it works only if I generate some events inside the window but in the same time if I change the active window by clicking on the top of window (can I call it label of the window? I don't know how it is called) it doesn't work.

My issue is that I need always know what window is on the focus. That is why `eventFilter` is not the best choice for my case because the window focusing maybe changed not only by clicking on it (or on a label) but also by clicking on small triangle wich is popupmenu (on the picture) in tabbed dockwindow.

What would you recommend me? How to know when the focued window has changed?
![1](https://user-images.githubusercontent.com/43808863/81626424-53818a80-9404-11ea-8ea5-ff8734355c37.png)

**Comment by githubuser0xFFFF** [comment]
I think i the final implementation will have some signals that will tell you which dock widget has the focus. Because this feature is under development, I would like to ask you to move this question into issue #163 to prevent a lot of issues popping up for features that are not ready yet.

Thank you.
