### ISSUE TITLE
Floatable Window always on the top of Mainwindow

### ISSUE THREAD

**Issue by chinakook** [githubuser0xFFFF/Qt-Advanced-Docking-System#275]
After dragging a dock widget into a floating window, it is always on the top of Mainwindow. How can I change this to make the Mainwindow on the top?

**Comment by githubuser0xFFFF** [comment]
This is not possible. This is not a special feature of ADS - if you test Microsoft Visual Studio, you will see the same behaviour.

**Comment by hcaihao** [comment]
Microsoft Visual Studio 2019 can make the Mainwindow on the top.

**Comment by chinakook** [comment]
> Microsoft Visual Studio 2019 can make the Mainwindow on the top.

+1

**Comment by ioanachelaru** [comment]
I'm also interested in this feature, it would be helpful to have the floating window in the background, if not even minimized, but I understand that minimization would be more complicated.

**Comment by githubuser0xFFFF** [comment]
I reopened the issue, in case someone will try to implement this

**Comment by dail8859** [comment]
I took a look at this as well since I'm interested in it. I noticed `QDockWidget`s have the same behavior of always being on top. According to [this](https://forum.qt.io/topic/39402/solved-qdockwidget-disable-always-on-top) thread you can't show a child widget underneath its parent.

For fun I edited this line:

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/12ec819aeb48c416bd25fb27eb49a853d0f95c83/src/FloatingDockContainer.cpp#L600

And passed in `Q_NULLPTR` instead of `DockManager`. It does partially give you the behavior of being able to have floating widgets behind the MainWindow...**however** it leads to alot of odd and undesirable behavior (missing styling, can't drag a floating window overtop the main window etc).

Not sure if this is a 'step in the right direction' and needs more work...or if this was a 'very dumb idea' and can never work correctly.

**Comment by githubuser0xFFFF** [comment]
It is technically not possible in Qt and therefore I close this issue for now
