### ISSUE TITLE
Add feature to be able to save locations for DeleteOnClose widgets

### ISSUE THREAD

**Issue by rolivav** [githubuser0xFFFF/Qt-Advanced-Docking-System#291]
Now that we can set widgets to be DeleteOnClose, it is not possible to save where the widgets were located before they were closed. 

The benefits of deleting widgets are several: it helps a lot when debugging the application (specially when widgets talk between them) and it gives you the possibility to reduce the amount of memory the application uses by closing expensive widgets. It saddens me that we lose the ability to restore its position when the user wants to show it again.

It should be possible to provide widget creator lambdas to the docking system so that it works exactly the same way as when using the default hide and show functionality. My idea would be to add something like this in DockManager:
```cpp
QMap<QString,  std::function<CDockWidget* ()>> mWidgetCreators;
```
so you could pass lambdas that return a CDockWidget* to the DockManager. The key of the map would be the object name so we can find it later.

When closing a widget, if we have DeleteOnClose and maybe another flag, the docking system would replace the widget with a hidden placeholder trivially constructed widget with the same object name instead of removing it completely from the layout (using [QLayout::replaceWidget](https://doc.qt.io/qt-5/qlayout.html#replaceWidget) ), so when saving we still end up with the same result as if it was just hidden when calling `CDockManager::saveState`. When showing the widget, it would check if it is a placeholder widget and try to create the real one using the creator functions and replace it.

This would give us all the benefits: the amazing layout saving while at the same time being able to delete widgets when closing. 

The tricky part is that the placeholder widgets would need to not appear when looking for CDockWidgets with that name. It will be easy to control this when using `CDockManager::findDockWidget`, but I am not sure if we can find hidden widgets with `findChildren<CDockWidget*>` right now. It might be difficult to avoid that.

Anyway, this was just an implementation proposal, I'd like to know your thoughts.

**Comment by githubuser0xFFFF** [comment]
Thank you for your proposal. I do not see the requirement for such a feature and I think it is a very "special" feature that is not required and requested by many people. So at the moment I'm not convinced to implement this special feature or to add a lot of code to ADS because of this feature. There are many applications out there, including our appication, with "expensive" widgets and I do not see the requirement to delete any widgets. 

There are other features in the issue list that are much more important (like autohide feature). You can try to create a pull request, but I cannot guarantee, that I will merge it. If the changes are small enough then maybe.

**Comment by rolivav** [comment]
I do not feel it is such a special feature, it is adding better support for the DeleteOnClose functionality that already exists. I do not understand why DeleteOnClose was originally added then if you felt it wasn't necessary. It strikes me as odd that you would immediately close this proposal.

I'll create a PR when possible. I hope you will reconsider once you see the implementation.

**Comment by githubuser0xFFFF** [comment]
Is this a feature that you would like to have because you think it is nice or do you have a specific requirement in your application? I always try to understand the intention of a feature request? So what is the specific requirement of your application and where can I find your app?

DeleteOnClose was added to support source code editors, where you don't keep all the 3000 source files of a project open in editors but delete closed editors.

I closed the issue, because I don't think it is important for ADS (sorry) and I do not want to have an endless list of open issues in this project.

**Comment by rolivav** [comment]
You are right, maybe explaining my use case in depth will help you understand.

The application I'm working on has widgets that are created from python using PyQt. These are what we call "plugins" created by users in their projects. The application doesn't know about these plugins until the user opens a project. At that point, we restore the layout for the current project, except for the plugins which are not opened in any way. The reason is that these plugins are expected to be deleted when closing them, and recreated each time they try to open them from the menu. 

A feature we have been requested is to open the projects with their plugins already in the layout where they left them. I can't currently support having these plugins delete on close and at the same time appear on the layout where they were, since this functionality is not available in ADS. It is a much more important feature that these plugins delete when closing, since that is the way the users iterate to create their plugins.

If you can think of a different way of achieving this, I'm all ears :) . I just genuinely thought that was the most scalable solution and a neat feature for other ADS users to use.

Also I am sorry, the application I work on is an internal tool and it is not available to the public in any way or capacity.
