### ISSUE TITLE
Docking notifications

### ISSUE THREAD

**Issue by ThomasKroes** [githubuser0xFFFF/Qt-Advanced-Docking-System#293]
This issue has some relation to issue #292. Perhaps someone has already asked this question, but I have not found this particular question during my search through the issues. I am sorry ahead if my question is a duplicate!

I was wondering if there are notifications that signals:
- When the docking process begins/ends
- When a dock widget is dropped into a dock widget area
- That a dock widget starts/stops floating
- When a dock widget is added/removed to/from a dock widget area

I have been looking in the headers of ``CDockManager``, ``CDockWidgetArea``, ``CDockWidget`` to see if there are any Qt signals for them, but have not found these (perhaps I am overlooking them).

I would be in favor of adding these extra notifications as they might be helpful to implement more advanced custom behavior.

What do you think?

**Comment by githubuser0xFFFF** [comment]
If you need additional notification signals, then feel free to create a pull request. I would prefer if you only add signals that you really need and not signals that you thing would be nice to have in the library for the future. You can always add additional signals later, if you require them for your application.

If you only require the signals because of issue #292 then I would prefer fixing the issue. I will look into it in the next days.

**Comment by jskardas** [comment]
You might take a look at the issue #268 and the suggested approach.

**Comment by githubuser0xFFFF** [comment]
@jskardas  There was never any pull request for the mentioned issue so I closed it.

**Comment by ThomasKroes** [comment]
@githubuser0xFFFF I totally agree, we should avoid code pollution with all sorts of edge-case signals. I will try to limit the signals to the once that can be of real value :)

**Comment by githubuser0xFFFF** [comment]
Ok, I will close the issue for now. Fell free to create a pull request.
