### ISSUE TITLE
Crash During Restore State

### ISSUE THREAD

**Issue by nilocFluid** [githubuser0xFFFF/Qt-Advanced-Docking-System#3]
In `DockContainerWidgetPrivate::restoreDockArea()` if a child widget of a dockarea can't be found with `findDockWidget()`, and that is the **ONLY** child of the dockarea :

```
if (!DockArea->count())
{
	delete DockArea;
	DockArea = nullptr;
}
else
{
	DockArea->setProperty("currentIndex", CurrentIndex);
}
CreatedWidget = DockArea;
DockAreas.append(DockArea);
```

`DockAreas` now contains a null pointer.

When control returns to `CDockManager::restoreState()` :
```
for (auto DockContainer : d->Containers)
{
	for (int i = 0; i < DockContainer->dockAreaCount(); ++i)
	{
		CDockAreaWidget* DockArea = DockContainer->dockArea(i);
		int CurrentIndex = DockArea->property("currentIndex").toInt();
		if (CurrentIndex < DockArea->count() && DockArea->count() > 1 && CurrentIndex > -1)
		{
			DockArea->setCurrentIndex(CurrentIndex);
		}
	}
}
```

At some point `DockArea` will be a null pointer, and the program will crash when it is dereferenced.

**Comment by githubuser0xFFFF** [comment]
Hi,

thank you for the report. I just uploaded my latest changes. It also contains some fixes in the restore functionality. Could you please test, if the error still exists. If it is still there, could you please provide sammple aplication (your application) and the saved ini file tor reproduce the problem here.

I will try to fix this quickly.

Uwe

**Comment by githubuser0xFFFF** [comment]
I just pushed a fix, that should solve this issue. The problem only occurs if you try to restore the state for dock windows that do not longer exist - for example if they have been renamed in source code.
