### ISSUE TITLE
Several ActivationChange event on undocking dock widget

### ISSUE THREAD

**Issue by DimaKoltun** [githubuser0xFFFF/Qt-Advanced-Docking-System#355]
Hi! If you define ADS_DEBUG_PRINT and run AdvancedDockingSystemDemo with flag
`
CDockManager::setConfigFlag(CDockManager::FocusHighlighting, true);
`
You can see, that when you undock widget from tabbar with several tabs happen next: 
1) focus from tab go to undocked widget
2) focus from undocked widget go to active tab in tabbar
3) focus from tabbar return to undocked widget

I think that should happen step 1, without 2, 3, what do you think about this?

https://user-images.githubusercontent.com/83829508/133738379-eeb68282-b048-4724-abe3-da6e9946fed7.mp4

**Comment by rolivav** [comment]
It's a common focus chain. The important part is that the focus ends up in the right place, is this impacting you in any way?

**Comment by githubuser0xFFFF** [comment]
@DimaKoltun Do you use the latest version from master branch?

**Comment by DimaKoltun** [comment]
@githubuser0xFFFF, yes

**Comment by DimaKoltun** [comment]
@rolivav , i didn't check how it work in qt, but i think only undocked tab should get focus. Some systems can do something when visibilityChanged() (signal in CDockWidget) for example, and if this signal emitting 3 times it's not ok

**Comment by gorec323** [comment]
This error cannot be reproduced on Linux.

**Comment by dail8859** [comment]
Just wanted to drop a note here that I'm experiencing the same thing (I'm on Windows, cannot speak for Linux) with the current master branch.

This is currently a bit of an annoyance since every time a `CDockWidget` is focused the application hits the file on disk, updates the UI components, etc. Since it switches back and forth it is doing extra processing.

Relevant portion from my debug output with some comments:

```
[     0.386] I: ~~~~~~~~~~~focusedDockWidgetChanged~~~~~~~~~~~~~~
[     0.387] I: New CDockWidget: New 1 // Very first widget
[     2.198] I: ~~~~~~~~~~~focusedDockWidgetChanged~~~~~~~~~~~~~~
[     2.198] I: Old CDockWidget: New 1
[     2.198] I: New CDockWidget: New 2 // Correct since new 2 was just created
[     9.662] I: ~~~~~~~~~~~focusedDockWidgetChanged~~~~~~~~~~~~~~
[     9.662] I: Old CDockWidget: New 2
[     9.662] I: New CDockWidget: New 1 // Dropped new 2 into a new area, but focuses on new 1
[     9.710] I: ~~~~~~~~~~~focusedDockWidgetChanged~~~~~~~~~~~~~~
[     9.710] I: Old CDockWidget: New 1
[     9.711] I: New CDockWidget: New 2 // Focuses back on new 2 immediately
[     9.730] I: ~~~~~~~~~~~focusedDockWidgetChanged~~~~~~~~~~~~~~
[     9.730] I: Old CDockWidget: New 2
[     9.730] I: New CDockWidget: New 2 // And again
```

The application starts off with widget `New 1`. Adds `New 2` and appropriately switches to it. At that point I drag `New 2` into a newly created area and the focus changes a few times which seems odd.

When I get a bit of time I'll look into this more and try to bisect and find a commit that started causing this.

**Comment by dail8859** [comment]
So I kind of understand the issue.

`DockContainerWidgetPrivate::moveToContainer` is first removing `New 2` from the first DockArea (which triggers a focus changes since that area needs to maintain focus on a DockWidget).

Then it is added to a newly created DockArea. Once that DockArea is added to the Splitter, this triggers a focus changes again. 

Finally as part of `CDockContainerWidget::dropWidget` it is calling `notifyWidgetOrAreaRelocation()`.

---

Ideally the first two reasons for it being triggered could in some way be blocked, and the final call to `notifyWidgetOrAreaRelocation()` would be the true final state which should show it switching from the old widget (`New 1`) to the new one (`New 2`).

There are alot of intricacies with all the focus stuff so I'm not sure I have any suggestions as to a good solution.

**Comment by githubuser0xFFFF** [comment]
Nobody wants to fix this - so it is no issue.
