### ISSUE TITLE
No solution to redock when close button clicked

### ISSUE THREAD

**Issue by ioanachelaru** [githubuser0xFFFF/Qt-Advanced-Docking-System#375]
Hello,

I need some help since I can't seem to find a function that will redock my widget. QDockWidget has `setFloating(bool)` that does exactly that, is there an equivalent for it? 
Also, I tried handling the close button's behaviour by setting the flag `CustomCloseHandling` and connecting to the `closeRequested()` signal, but it does'n seem like the signal is emitted. Am I doing it wrong or is there something missing? 

Thanks in advance

**Comment by githubuser0xFFFF** [comment]
Hi,

redocking with `setFloating(false)` ist not supported because it is technically not possible. In the Qt docking system you have dock areas that are always there - that means you can simply redock the floating widget to its previous docked area. In ADS you can dock the floating widget anywhere. That means, if the floating widget was docked into a dock area that does not exist anymore or into a floating widget that is closed or deleted, then it is not possible to redock it.

Regarding `CustomCloseHandling`: please have lock into the demo application to see how it works and how to use it.
