### ISSUE TITLE
Question to restore/save state

### ISSUE THREAD

**Issue by steffenroeber** [githubuser0xFFFF/Qt-Advanced-Docking-System#417]
Hi,
I have a question to the restoring and saving state information.
Following use case: I have instances of CDockWidget. Then I save the state and close the app.
Later I restart the app creating some of the CDockWidget, restoring their states, all works fine.
But, if I have widgets that I create after restoring state, how can I handle this if I want to restore only the single widget? Is there any way? Currentlym I restore the whole dockmanager in this case, or is there any better way? I guess (but nor sure), QMainWindows restore state creates some dummy placeholder depending on the objectName and later puts those widgets into these placeholder. Has your lib a similar feature?

**Comment by steffenroeber** [comment]
Remark. Same for widgets I close, delete and re-open. I want to put those widgets at the same state as before close.

**Comment by githubuser0xFFFF** [comment]
The restore state function restores the state of existing dock widgets - that means, if a widget does not exist, its state cannot be restored.

> Remark. Same for widgets I close, delete and re-open. I want to put those widgets at the same state as before close.

This is not supported by the library. You need to implement this by yourself. But this will be quite difficult. Because your user may have added or removed dock widgets to the layout. In this case it is not easy do decide, where to insert the widget.
