### ISSUE TITLE
CDockFocusController not available if FocusHighlighting is set after Creating the manager

### ISSUE THREAD

**Issue by Murmele** [githubuser0xFFFF/Qt-Advanced-Docking-System#482]
```cpp
m_DockManager = new ads::CDockManager(this);
m_DockManager->setConfigFlag(ads::CDockManager::XmlCompressionEnabled, false);
m_DockManager->setConfigFlag(ads::CDockManager::FocusHighlighting, true);
connect(m_DockManager, &ads::CDockManager::focusedDockWidgetChanged, this, &MainWin::dockFocusChanged);
```

The problem is that the focus controller is only created if the flag is already set when creating the manager, but not if I call setConfigFlag afterwards.
```cpp
CDockManager::CDockManager(QWidget *parent) :
	CDockContainerWidget(this, parent),
	d(new DockManagerPrivate(this))
{
	createRootSplitter();
	createSideTabBarWidgets();
	QMainWindow* MainWindow = qobject_cast<QMainWindow*>(parent);
	if (MainWindow)
	{
		MainWindow->setCentralWidget(this);
	}

	d->ViewMenu = new QMenu(tr("Show View"), this);
	d->DockAreaOverlay = new CDockOverlay(this, CDockOverlay::ModeDockAreaOverlay);
	d->ContainerOverlay = new CDockOverlay(this, CDockOverlay::ModeContainerOverlay);
	d->Containers.append(this);
	d->loadStylesheet();

	if (CDockManager::testConfigFlag(CDockManager::FocusHighlighting))
	{
		d->FocusController = new CDockFocusController(this);
	}


.
.
.
```

![image](https://user-images.githubusercontent.com/10099533/214827153-efc0ce4c-e7c8-40f2-903a-f139a11f8946.png)

commit id: 7b30322946fe77d9d680edcfac1df4035cc765f5

**Comment by githubuser0xFFFF** [comment]
Yes, this is right and this is how it is documented in the documentation:

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/master/doc/user-guide.md#configuration-flags

This is what the manual says:

_"You must set the configuration flags before creating the dock manager instance otherwise the manager will not be created correctly and will crash upon being created. That means, setting the configurations flags is the first thing you must do, if you use the library."_

**Comment by Murmele** [comment]
@githubuser0xFFFF thanks for the clarification!
