### ISSUE TITLE
Docking floating windows and WSL2/WSLg/Wayland

### ISSUE THREAD

**Issue by jonjenssen** [githubuser0xFFFF/Qt-Advanced-Docking-System#486]
The latest WSL updates for both Windows 11 and Windows 10 allows you to run Linux GUI applications on your Windows desktop, and we are using that during development of a cross platform application with great success.

The only thing not working is redocking floating widgets.

Your latest update that checks if native windows should be used or not by looking at the XDG_SESSION_TYPE environment variable seemed promising, but when running Ubuntu in WSL, that variable is empty. So the check for Wayland fails to detect that Wayland is used, and native windows are selected.

You can however update the check to look at i.e. "WAYLAND_DISPLAY", and if that is none-empty stop using native window, something like:

		QString WaylandDisplay = qgetenv("WAYLAND_DISPLAY").toLower();
		if (WaylandDisplay != "")
		{
			native_window = false;
		}

(FloatingDockContainer.cpp, line 681)

This brings up the docking clues in the GUI when dragging the floating window, but once you drop the window somewhere, nothing happens, the window is not re-docked at the selected position, but keeps on being a floating window.

Do you have any clue why this happens. It seems to be very close to working.

**Comment by githubuser0xFFFF** [comment]
No, Sorry I have no glue. And I must admit that I have given up fixing such things for Linux. 90% of all reported issues are because of the heterogeneous Linux environment with different window managers, compositors and supported features - this is so frustrating.

I use ADS in a Windows application without problems since years. I will try to keep ADS working on the most recent Ubuntu LTS versions. All other problems need to get fixed by Linux ADS users.

So thank you so far, that you try to fix this issue and I would be happy to get a pull request, if you succeed.

**Comment by jonjenssen** [comment]
With the check I mentioned above and adjusting the window hint, I am able to redock floating windows when using WSL (which uses wayland).

Ref. [this commit](https://github.com/CeetronSolutions/qtadvanceddocking/commit/e727c255bcf8b34d7877065ae88983e9b421e108)

**Comment by CarlSchwan** [comment]
This should be easier to implement now that this protocol is merged https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/204

**Comment by githubuser0xFFFF** [comment]
No progress - closing this issue
