### ISSUE TITLE
Laggy movement of floating window

### ISSUE THREAD

**Issue by PlasmaMichael** [githubuser0xFFFF/Qt-Advanced-Docking-System#53]
Hi,
If you detach a dock widget and stay clicked and move around, the floating window is moving very laggy. When you release the click, so the detached window doesn't move anymore, and then move the floating window again, it's not laggy anymore.

**Comment by githubuser0xFFFF** [comment]
Could you please test this with Qt5.12 to verify that this is a problem of Qt5.13 - thank you.

**Comment by githubuser0xFFFF** [comment]
Please report all issues that are caused by Qt5.13 in this bug. I closed you other issues.

**Comment by githubuser0xFFFF** [comment]
I just tested the AdvancedDockingSystemDemo.exe app with Qt 5.13.1 and could not reproduce the problem. Could you please give some instructions what I need to do to reproduce the problem in the AdvancedDockingSystemDemo.exe application. Maybe you could provide a video where I can see what is going on. Here on my Windows 10 machine with Qt 5.13.1 everything is smooth.

**Comment by PlasmaMichael** [comment]
Instead of having multiple bug ticket, I agree that one ticket to discuss, I answered here:
https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/issues/52

**Comment by githubuser0xFFFF** [comment]
I tested this with Qt5.13.1 and could not reroduce the problem on Windows. I cannot reproduce the problem with the demo application and I also do not see the problem in our big QmixElements application (screenshots of the dark themed application). So I do not think that this is a Qt5.13.1 problem.

Because I do not know what you are doing in you application, It is difficult to say, what the exact problem is. Maybe you filter some events that are required for the docking system to work properly.

**Comment by PlasmaMichael** [comment]
The original Docking system of Qt works perfectly so there must be something but yes difficult to say what is really happening. I tried to integrate this docking system in a full 3D engine editor which also contains a custom tabbed window like Chrome tab system, each tab contains one QMainWindow and the QMainWindow is full of dock windows. I will certainly bypass the use of this system because of the multiple things I mentioned to #52 but I have to say that this is still a great job.
