### ISSUE TITLE
Please add a new signal in DockManager whenever any DockWidget's area changed.

### ISSUE THREAD

**Issue by ChivenZhang** [githubuser0xFFFF/Qt-Advanced-Docking-System#545]
I need to save the whole docking state urgently whenever the user changing the dockarea of widget, such as docking, floating, auto-hiding and so on. So it's helpful if there is a new signal in dock manager, such as "void dockWidgetAreaChanged(ads::CDockWidget* DockWidget);".
Thanks

**Comment by githubuser0xFFFF** [comment]
What do you mean with "save the whole docking state"?

**Comment by Jakhontoviy** [comment]
> What do you mean with "save the whole docking state"?

@githubuser0xFFFF, I would like setup different windows in my software like this in this example for instance:

![2023-10-18_19h34_09](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/79797608/5b11fcb7-25fd-4fed-9779-3a549f7972b6)

Then I'd like to save this state, close my software, open it agait and restore all windows in exactly same position as they were before.

As far as I understand, it is not possible in current release, but I believe it is crucial for many developers who uses your great solution. So I'd like to contribute if it is not in your roadmap yet. 

Regards.

**Comment by Jakhontoviy** [comment]
@githubuser0xFFFF sorry that I was not perfectly clear in my problem definition. We've tried all options before decided to spend your time. So, here is more complete description:

1. In my example I have 1 container at the right part of my software. Container consist of 2 windows - first on the top of container and second on the bottom:

![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/79797608/3cc4caef-df37-4d60-b2da-607cfeee04fc)


2. When I save this state and restore it, both windows change their states and user see them as tabs in the same container:

![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/79797608/263fcdc1-1594-41f6-9088-af700ba14f70)

So, we didnt find the way to save position of windows inside the container and restore them in exactly same position in relation to another windows in the same container (top-bottom, left-right, etc).

Could you please help us if it is already possible. If it is not, please consider to add this useful feature or give us technical advice how to implement it to be accepted on your side and we'll perform this development as fast as possible since it is crucial for our project.

**Comment by githubuser0xFFFF** [comment]
Please have a look into the demo to see how the state is saved and restored and how perspectives work.

**Comment by Injer** [comment]
Thanks, saveState() is just what we are looking for !

**Comment by githubuser0xFFFF** [comment]
@Jakhontoviy 

> We've tried all options before decided to spend your time.

:joy::joy::joy: - No comment.
