### ISSUE TITLE
Licensing under LGPL 3.1

### ISSUE THREAD

**Issue by AndreMeyerRMC** [githubuser0xFFFF/Qt-Advanced-Docking-System#561]
Since the LGPL 2.1 seems to have some open issues when it comes to inline and template functions, and the LGPL 3.1 seems to mitigate that, would it be possible to switch or extend the licensing model to LGPL 3.1?
There are just a very few short inline and template functions in the headers, and they are probably possible to avoid with writing an extra wrapper, but since I guess the licensing should allow to incorporate QADS in commercial projects, would it be possible to update the license?

**Comment by githubuser0xFFFF** [comment]
No, I prefer the 2.1 version.

**Comment by AndreMeyerRMC** [comment]
Sorry to hear that, thank you for checking.

**Comment by thorntonryan** [comment]
We had a similar question and noted that the source code explicitly mentions using a later version... was this intentional?

https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/blob/5f3580bba5c83d4f200897b80f0bca88b9cba56c/src/AutoHideSideBar.h#L10

https://github.com/search?q=repo%3Agithubuser0xFFFF%2FQt-Advanced-Docking-System+%22any+later+version%22&type=code

Another option, perhaps, Qt likewise was long using LGPL v2.1 but with an exception clarifying inline templates in headers, which importantly drops the 10 lines or less restriction and is similar to the language used by LGPLv3

> The Qt Company Qt LGPL Exception version 1.1
> 
> As an additional permission to the GNU Lesser General Public License version
> 2.1, the object code form of a "work that uses the Library" may incorporate
> material from a header file that is part of the Library.  You may distribute
> such object code under terms of your choice, provided that:
>     (i)   the header files of the Library have not been modified; and 
>     (ii)  the incorporated material is limited to numerical parameters, data
>           structure layouts, accessors, macros, inline functions and
>           templates; and
>     (iii) you comply with the terms of Section 6 of the GNU Lesser General
>           Public License version 2.1.
> 
> Moreover, you may apply this exception to a modified version of the Library,
> provided that such modification does not involve copying material from the
> Library into the modified Library's header files unless such material is
> limited to (i) numerical parameters; (ii) data structure layouts;
> (iii) accessors; and (iv) small macros, templates and inline functions of
> five lines or less in length.
> 
> Furthermore, you are not required to apply this additional permission to a
> modified version of the Library.

https://code.qt.io/cgit/qt/qtbase.git/tree/LGPL_EXCEPTION.txt?h=v5.11.0

Would you consider a clarifying LGPL Exception similar to what Qt used to do?

**Comment by githubuser0xFFFF** [comment]
According to the license text you can use LGPLv3
