### ISSUE TITLE
Window Layouts become "messed up" with multiple monitors.

### ISSUE THREAD

**Issue by imikejackson** [githubuser0xFFFF/Qt-Advanced-Docking-System#614]
This is our app when launching on my main monitor:

![Screenshot 2024-03-20 at 14 17 44](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/5182396/f32df612-2972-4f9a-b2af-bd9eaa8b9f14)

When we quit the application we save the layout, using the QtADS built in methods, to a preference file. If I relaunch the application but have it launch on my secondary monitor I get the following instead:

![Screenshot 2024-03-20 at 14 17 59](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/5182396/203179d0-8a4f-40f2-8824-fce401381f60)

Has anyone ever seen this?

We are using commit ed6636a

**Comment by imikejackson** [comment]
Latest commit does not fix the issue. I'm sure this is a "user" error on our part?

**Comment by githubuser0xFFFF** [comment]
Do you use different scaling on on both monitors? That means monitor 1 uses 100% scaling and monitor 2 uses 150%.

Btw. when providing bug reports you should provide the following information:

OS: Windows / Linux
Qt Version: 5.15.2 or 6.6.2 ....
Compiler: MinGW, MSVC17...

Btw, even QWidget::restoreGeometry does not work properly on a multi-monitor system:

https://bugreports.qt.io/browse/QTBUG-70721

So maybe this is an issue caused by using different DPIs on different monitors - I'm just guessing.
