### ISSUE TITLE
How can I fix dock width?

### ISSUE THREAD

**Issue by soryeongpark** [githubuser0xFFFF/Qt-Advanced-Docking-System#630]
![image](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/assets/160213036/5de5dff8-a1dc-4c3b-89f2-d44f8a9a2181)

Hi. First of all, thank you for providing such a great feature.
I want to prevent the width of the docking widget from decreasing further so that horizontal bars do not appear.
What can I do?

Plus, How can I fix docking widget size?

Thank you.

**Comment by githubuser0xFFFF** [comment]
Please have a look into the `eInsertMode` enum in `DockWidget.h` and `eMinimumSizeHintMode` and play around with it, to find out, if you can find a solution.

I would not recommend to restrict the size of any dock widget because this will block your dock system sizes. If there is a scroll bar, the user can easily adjust the dock widget with in a way that the scroll bar will disappear.
