### ISSUE TITLE
Crash when docking and undocking a Qt3D window

### ISSUE THREAD

**Issue by m4na7n** [githubuser0xFFFF/Qt-Advanced-Docking-System#81]
I have encountered almost the exact same issues as was reported in #52 #53. That is, if you start dragging certain windows (in my case it only happens with Qt3D windows) the movement is laggy. But if you release and start moving the window again the movement is smooth. However, if you dock that window somewhere and then try undock it by moving it the application crashes.

I can reproduce this issue on both Windows and Linux with both Qt 5.13 and 5.14. I think it has something to do with windows that are bit demanding to draw. Since it only happens with Qt3D windows with some contents and it easier for me to trigger with debug builds.

Patch that adds a Qt3D window to the demo application that triggers the issue for me:
[Qt3D.txt](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/files/3854424/Qt3D.txt)

Valgrind output from Qt 5.14 from one crash:
[valgrind.txt](https://github.com/githubuser0xFFFF/Qt-Advanced-Docking-System/files/3854430/valgrind.txt)

**Comment by githubuser0xFFFF** [comment]
Moving a floating window and dragging a dock widget out of its docking position is completely different in terms of implementation. If you move a floating window, then the window movement is handled by the operating system. That means, the OS captures the mouse click and move events in the window title bar and moves cares about window movement - this seems to work fine.

When dragging a dock widget out of its docking position, the window movement is handled completely by the advanced docking system. That means, the ADS needs to capture mouse clicks and mouse movements and needs to move the window via the QWidget move function. This is implemented in the CFloatingDockContainer::moveFloating() function. So there is nothing special about this function, is just calculates the new position and calls QWidget::move(). As soon as you release the mouse, you have a floating window and the next time you move it, the OS cares about the movement.

I will try to test your patch to reproduce the issue here. In my application I have never seen this problem.

A idea to solve this problem, would be, to leave the docked window in its position while dragging it out of its docking state and to just move around some kind of dummy transparent window with a highlighted border to indicate the future position - like if you disable opaqueResize() for QSplitter and then drag a splitter around. That means the real docked window will only be moved to the new position when the mouse button is released.

**Comment by m4na7n** [comment]
I have performed some more tests and I learned some new information.

First, now I can only seem to trigger this issue on Windows and I rarely get the crash I used to get before. So the crash might be unrelated to the "laggy" movement.

As for the laggy window movement I found that the issue is that ADS does not receive the mouseMoveEvent when moving the mouse in the title bar area. The window is only moved when the mouse exits this area, which results in "laggy" movement. However, it only happens if I first dock in one of the left, right, top or bottom dock areas and then undock it by dragging the title bar. If I dock into the center area, I can smoothly undock and move the window by dragging the the title bar.

The only difference I could find is that in FloatingDockContainer::event the last call to QWidget::event(e) returns true in the case where the window is smoothly updating and false when it is laggy.

**Comment by githubuser0xFFFF** [comment]
Do you get laggy movement for the demo application or ist related to Qt3D  windows?

**Comment by githubuser0xFFFF** [comment]
Could you provide a sample application that shows the isuue?

**Comment by m4na7n** [comment]
> Do you get laggy movement for the demo application or ist related to Qt3D windows?

It is the floating windows in the demo application that are laggy. The Qt3D window is made into a QWidget with QWidget::createWindowContainer so it can be managed be ADS. And the laggy movement affects all floating windows that are undocked by dragging the title bar, as long as the Qt3D window is created. If I don't add the Qt3D window to the DockManager then everything works as expected.

**Comment by m4na7n** [comment]
> Could you provide a sample application that shows the isuue?

The patch attached in the first comment triggers the issue for me. That is what I have been using when I tried to troubleshoot this issue.

The following steps always reproduce the issue for me.

1. Undock any window (does not have to be the Qt3D window)
2. Dock that window in either a left, right, top or bottom dock area of some other widget (not the center area)
3. Undock the same window by dragging the titlebar (don't release the mouse) and observe that the floating window is not moved, unless the mouse moves out of the title bar area. Only then is the floating window moved.

**Comment by githubuser0xFFFF** [comment]
Ok, then this problem is related to Qt because it does not occur with Qt 5.12.2. Please tell me your exact Qt version.

**Comment by githubuser0xFFFF** [comment]
So the problem only occurs for the floating window with Qt3D content - the rest of the demo works fine?

**Comment by m4na7n** [comment]
I have to double check the exact version tomorrow, but I know it is 5.13.x and I think it is 5.13.1

**Comment by m4na7n** [comment]
> So the problem only occurs for the floating window with Qt3D content - the rest of the demo works fine?

Actually I found out today that the problem affects all floating windows, as long as I have added the Qt3D window to the DockManager. If I don't add the Qt3D window to the DockManager then everything works as expected. But I will try on another Windows computer and see if I can reproduce the issue there as well.

**Comment by githubuser0xFFFF** [comment]
I can reproduce the problem with your patch here. The problem is clearly related to the 3D content. The 3D scene somehow captures the mouse events. If I drag a docked widget with 3D content, then I can see, the the vieport of the 3D scene changes. That indicates that the mouse events are captured by the 3D scene

**Comment by m4na7n** [comment]
The odd thing is that it does not happen when I dock to the center area of another widget. If I dock the center area I can undock the window by dragging and the movement of the floating window is smooth.

**Comment by githubuser0xFFFF** [comment]
I think the problem is related to the Qt3DWindow embedded into a QWidget. You need to find out, what the window and widget do with the mouse events

**Comment by githubuser0xFFFF** [comment]
I just pushed some changes that add support for non opaque undocking. That means, if a dock widget is dragged from a docked position, then no floating widget is created but only a static preview widget like it is done for othe drag & drop operations. The dock widget is created, as soon as you release the mouse button.

To enable this feature, you only have to set some CDockManager config flags. You just need to uncomment the line

**CDockManager::setConfigFlags(CDockManager::DefaultNonOpaqueConfig);**

in line 330 of the demo application MainWindow.cpp.

I tested your Qt3D.txt patch with these changes and it worked so far. Please test if non opaque undocking works for Qt3D content.

**Comment by m4na7n** [comment]
I just tested the latest code with the non opaque undocking and it works great for me. Thanks alot!

When I find some time later on I will investigate what the actual problem was with the missing mouse events in the "regular" mode.

**Comment by githubuser0xFFFF** [comment]
Great that it works. I would say, there is no "regular" mode. I like the non opaque undocking and I think it has some advantages. For example it will be possible in the future to cancel the undocking with a key.

So I think opaque and non opaque undocking are two different modes with different advantages.
